#!/usr/bin/env bash
# Usage: jiff reinstall [package]
# Summary: Reinstall a system package

source stdlib
source jifflib # jiff-specific functions
source distrolib # distribution-specific functions

strict_mode on

package="${1}"

run_and_exit_if_is_jiff_task "${package}-reinstall"
reinstall_package "${package}"
