#!/usr/bin/env bash
# Usage: jiff task-edit

source std.sh

std::set_default "EDITOR" "/usr/bin/vim"

main() {
  local filename

  filename="jiff-$1"
  cd "${_JIFF_ROOT}/context/current"
  "${EDITOR}" "${filename}"
  git add "${filename}"
}

return 0 2>/dev/null || true
std::strict_mode on
main "$@"
