#!/usr/bin/env bash
# Usage: jiff config PACKAGE

source stdlib
source jifflib

Verb="config"

main () {
  run_subtask "${Verb}" "$@"
}

usage () {
  echo "Usage: jiff ${Verb} PACKAGE"
}

return 0 2>/dev/null || true
strict_mode on
main "$@"
