#!/usr/bin/env python2

import pytoml as toml
import sys, os

def main(argv):
    filename = os.path.join(os.path.dirname(__file__), "../context/current/data.toml")
    with open(filename, "rb") as datafile:
        contents = toml.load(datafile)
    branches = argv[0].split(".")
    print child(contents, argv[0])

def child(tree, spec):
    if "." in spec:
        branch, rest = spec.split(".", 1)
        return child(tree[branch], rest)
    return tree[spec]

if __name__ == "__main__":
    main(sys.argv[1:])
