#!/usr/bin/env bash
# Usage: jiff add TASK

source std.sh
source jiff.sh

Verb="add"

main () {
  jiff::run_subtask "${Verb}" "$@"
}

usage () {
  echo "Usage: jiff ${Verb} TASK"
}

return 0 2>/dev/null || true
std::strict_mode on
main "$@"
