#!/usr/bin/env bash
# Usage: jiff config [package]
# Summary: Configure a software package

source stdlib
source jifflib

declare -r WorkingDir="${HOME}/tmp"

main () {
  run_and_exit_if_is_jiff_task "${1:-}-config"
}

return 0 2>/dev/null || true
strict_mode on
run_in_directory "${WorkingDir}" "main" "${@}"
