#!/usr/bin/env bash
# Usage: jiff role

source stdlib

main () {
  local dirname="$(abs_dirname "${_JIFF_ROOT}/context/current/..")"
  make_symlink "${dirname}/role" "${1}"
}

return 2>/dev/null || true
strict_mode on
main "${@}"
