#!/usr/bin/env bash

source sh.sh
source array.sh

declare -r RoleLink="${_JIFF_ROOT}/role/current"
declare -r ContextLink="${_JIFF_ROOT}/context/current"

main() {
  local context
  local contexts
  local hostname
  local hosts

  jiff::is_file "${RoleLink}" || jiff role admin
  jiff::is_not_file "${ContextLink}" || exit 0
  contexts=( jiff _data -g hosts.keys )
  hostname="$(hostname)"
  for context in "${contexts[@]}"; do
    hosts=( jiff _data -g "hosts.${context}" )
    if ary::contains "${hostname}" "${hosts[@]}"; then
      jiff context "${context}"
    fi
  done
}

return 0 2>/dev/null || true
sh::strict_mode on
main "$@"
