#!/usr/bin/env bash
# Usage: jiff jiff-update
# Summary: Update jiff

source stdlib

# TODO: read deps from package.sh
main () {
  basher upgrade binaryphile/bash-libs
  basher upgrade binaryphile/jiff-core
  current="$(jiff context | tail -1 | cut -d " " -f3)"
  cd "${_JIFF_ROOT}"
  jiff context none
  git checkout -- .
  git fetch
  git reset --hard origin/master
  jiff context "${current}"
}

return 0 2>/dev/null || true
strict_mode on
main "${@}"
