#!/usr/bin/env bash
# Usage: jiff role [admin|user]

source stdlib
source jifflib
source arraylib
source stringlib

RoleLink="${RoleLink:-${_JIFF_ROOT}/role/current}"
ConextLink="${ContextLink:-${_JIFF_ROOT}/context/current}"

main () {
  local role
  local context

  role="${1:-}"
  if is_empty "${role}"; then
    usage
    report_current
    exit 0
  fi
  make_symlink "${RoleLink}" "${role}"
  if is_file "${ContextLink}"; then
    context="$( readlink "${_JIFF_ROOT}/context/current" )"
    context=( str_split "/" "${context}" )
    unset context["${#context}"-1]
    unset context[0]
    context="$(array_join "/" "${context[@]}")"
    jiff context "${context}"
  else
    make_rolelinks
  fi
}

available_roles () {
  # shellcheck disable=SC2010
  ls "${_JIFF_ROOT}/role" | grep -v current
}

report_current () {
  local current

  if is_link "${RoleLink}"; then
    current="$(readlink "${RoleLink}" | cut -d/ -f1)"
  else
    current=none
  fi
  cat <<EOM
Currently using: ${current}
EOM
}

usage () {
# TODO: fill in roles from $Roles
  cat <<EOM
Usage: jiff role ROLE

Available roles:

$(available_roles)

EOM
}

return 2>/dev/null || true
strict_mode on
main "${@}"
