#!/usr/bin/env bash
# Summary: choose a set of tasks based on context and, optionally,
# distribution
#
# Usage:
#   jiff set context [-d <distro>|--distro=<distro>] (<context>|none)
#
# Options:
#   <distro>    One of: rhel-6|centos-6|ubuntu-14|ubuntu-15
#   <context>   One of: avwob|armt|office|peak10

source stdlib
source arraylib
source jifflib

declare -r LibExecDir="${_JIFF_ROOT}/libexec"
declare -r DistroLink="${_JIFF_ROOT}/distro/current"
declare -r RoleLibLink="${_JIFF_ROOT}/lib/rolelib"
declare -r ContextLink="${_JIFF_ROOT}/context/current"
declare -r RoleLink="${_JIFF_ROOT}/role/current"

main () {
  local context
  local distro
  local distros

  context="${1:-}"
  distro="${2:-}"
  if is_empty "${context}"; then
    usage
    report_current
    exit 0
  fi
  if is_match "${context}" "none"; then
    remove_links
    make_rolelinks
    exit 0
  fi
  distros=( $(available_distros) )
  is_not_empty "${distro}" || distro="$(detect_os)"
  if ary_contains "${distro}" "${distros[@]}"; then
    remove_links
    make_rolelinks
    make_links "${context}" "${distro}"
    exit 0
  fi
}

available_contexts () {
  # shellcheck disable=SC2010
  ls "${_JIFF_ROOT}/context" | grep -v current
}

available_distros () {
  ls "${_JIFF_ROOT}/distro"
}

make_links () {
  local context
  local distro
  local role
  local file
  local task

  context="${1}"
  distro="${2}"
  is_link "${RoleLink}" || jiff role admin
  role="$(readlink "${RoleLink}")"
  make_symlink "${ContextLink}" "${context}/${distro}/${role}"
  make_symlink "${DistroLink}" "${distro}"
  make_symlink "${RoleLibLink}" "../distro/${distro}/${role}lib"
  for file in "${ContextLink}"/jiff-*; do
    is_match "${file}" "${ContextLink}/jiff-*" && continue
    task="$(base_name "${file}")"
    make_symlink "${LibExecDir}/${task}" "${file}"
  done
}

remove_links () {
  local file
  local link
  local links

  for file in "${ContextLink}"/jiff-*; do
    link="$(base_name "${file}")"
    rm -f "${LibExecDir}/${link}"
  done
  read -d "" -a links <<EOM || true
${ContextLink}
${DistroLink}
${RoleLibLink}
EOM
  for link in "${links[@]}"; do
    rm -f "${link}"
  done
}

report_current () {
  local current

  if is_link "${ContextLink}"; then
    current=$(current_context)
  else
    current=none
  fi
  cat <<EOM
Currently using: ${current}
EOM
}

usage () {
# TODO: fill in contexts from $Distros
  cat <<EOM
Usage: jiff context CONTEXT|none [rhel-6|centos-6|ubuntu-14|ubuntu-15]

Available contexts:

$(available_contexts)

EOM
}

return 0 2>/dev/null || true
strict_mode on
main "${@}"
