#!/usr/bin/env bash
# Usage: jiff reinstall [package]
# Summary: Reinstall a system package

source stdlib
source jifflib
source distrolib

declare -r WorkingDir="${HOME}/tmp"

main () {
  local package

  package="${1}"
  run_and_exit_if_is_jiff_task "${package}-reinstall"
  reinstall_package "${package}"
}

return 0 2>/dev/null || true
strict_mode on
run_in_directory "${WorkingDir}" "main" "${@}"
