#!/usr/bin/env bash
# Usage: jiff role [admin|user]

source sh.sh
source jiff.sh
source array.sh
source string.sh

declare -r LibExecDir="${_JIFF_ROOT}/libexec"
declare -r ContextLink="${_JIFF_ROOT}/context/current"
declare -r RoleLink="${_JIFF_ROOT}/role/current"

main() {
  local role

  role="${1:-}"
  if sh::is_empty "${role}"; then
    usage
    report_current
    exit 0
  fi
  remove_links
  if sh::is_match "${role}" "none"; then
    jiff set context none
    exit 0
  fi
  sh::make_symlink "${RoleLink}" "${role}"
  if sh::is_link "${ContextLink}"; then
    jiff set context "$(current_context)"
  else
    make_rolelinks
  fi
}

available_roles() {
  printf "%s" "${_JIFF_ROOT}/role/*" | grep -v current
}

remove_links() {
  local file
  local link
  local links

  for file in "${RoleLink}"/jiff-*; do
    link="$(sh::base_name "${file}")"
    rm -f "${LibExecDir}/${link}"
  done
  read -d "" -a links <<EOM || :
${RoleLink}
EOM
  for link in "${links[@]}"; do
    rm -f "${link}"
  done
}

report_current() {
  local current

  if sh::is_link "${RoleLink}"; then
    current="$(readlink "${RoleLink}")"
  else
    current=none
  fi
  cat <<EOM
Currently using: ${current}
EOM
}

usage() {
# TODO: fill in roles from $Roles
  cat <<EOM
Usage: jiff role ROLE

Available roles:

$(available_roles)

EOM
}

return 0 2>/dev/null || :
sh::strict_mode on
main "$@"
