#!/usr/bin/env bash
# Usage: jiff show

source std.sh
source jiff.sh

Verb="show"

main() {
  jiff::run_subtask "${Verb}" "$@"
}

usage() {
  echo "Usage: jiff ${Verb} TASK"
}

return 0 2>/dev/null || true
std::strict_mode on
main "$@"
