#!/usr/bin/env bash
# Usage: jiff show

source sh.sh
source jiff.sh

Verb="show"

main() {
  jiff::run_subtask "${Verb}" "$@"
}

usage() {
  echo "Usage: jiff ${Verb} TASK"
}

return 0 2>/dev/null || true
sh::strict_mode on
main "$@"
