#!/usr/bin/env bash
# Usage: jiff update PACKAGE

source stdlib
is_not_file "${_JIFF_ROOT}/lib/distrolib" || source distrolib
source jifflib

Verb="update"

main () {
  run_subtask "${Verb}" "$@"
  update_package "$1"
}

usage () {
  echo "Usage: jiff ${Verb} PACKAGE"
}

return 0 2>/dev/null || true
strict_mode on
main "$@"
