#!/usr/bin/env bash
# Usage: jiff jiff-update
# Summary: Update jiff

source stdlib

# TODO: read deps from package.sh
basher upgrade binaryphile/bash-libs
basher upgrade binaryphile/jiff-core
current="$(jiff context | tail -1 | cut -d ":" -f2)"
jiff context none
push_dir "${_JIFF_ROOT}"
git checkout -- .
git fetch
git reset --hard origin/master
jiff context "${current}"
pop_dir

return 2>/dev/null || true
strict_mode on
