#!/usr/bin/env bash
# Usage: jiff set

source sh.sh
source jiff.sh

Verb="set"

main() {
  jiff::run_subtask "${Verb}" "$@"
}

usage() {
  printf "Usage: jiff %s TASK\n" "${Verb}"
}

return 0 2>/dev/null || :
sh::strict_mode on
main "$@"
