#!/usr/bin/env bash
# Summary: show the current context
#
# Usage:
#   jiff show context

source file.sh
source jiff.sh
source shell.sh

# shellcheck disable=SC2034
declare -r ContextLink="${_JIFF_ROOT}/context/current"

main() {
  report_current
}

report_current() {
  local current

  if fil.symlink? ContextLink; then
    current="$(jiff.current_context)"
  else
    current=none
  fi
  cat <<EOM
${current}
EOM
}

return 0 2>/dev/null || :
sh.strict_mode on
main "$@"
