#!/usr/bin/env bash
# Summary: show the current context
#
# Usage:
#   jiff show context

source std.sh
source jiff.sh

declare -r ContextLink="${_JIFF_ROOT}/context/current"

main() {
  report_current
}

report_current() {
  local current

  if std::is_link "${ContextLink}"; then
    current="$(jiff::current_context)"
  else
    current=none
  fi
  cat <<EOM
${current}
EOM
}

return 0 2>/dev/null || true
std::strict_mode on
main "$@"
