#!/usr/bin/env bash
# Usage: jiff reinstall PACKAGE

source sh.sh
source distro.sh
source jiff.sh

Verb="reinstall"

main() {
  jiff::run_subtask "${Verb}" "$@"
  dist::reinstall_package "$1"
}

usage() {
  printf "Usage: jiff %s TASK\n" "${Verb}"
}

return 0 2>/dev/null || true
sh::strict_mode on
main "$@"
