#!/usr/bin/env bash
# Usage: jiff install [package]
# Summary: Install and configure a system package

source stdlib
source jifflib
source distrolib

main () {
  local package

  package="${1}"
  run_and_exit_if_is_jiff_task "${package}-update"
  update_package "${package}"
}

return 0 2>/dev/null || true
strict_mode on
main "${@}"
