#!/usr/bin/env bash
# Usage: jiff show

source shell.sh
source jiff.sh

Verb="show"

main() {
  jiff.run_subtask "$Verb" "$@"
}

usage() {
  printf "Usage: jiff %s TASK" "$Verb"
}

return 0 2>/dev/null || :
sh.strict_mode on
main "$@"
