#!/usr/bin/env bash
# Usage: jiff task-show TASK
# Summary: Show a jiff task

source sh.sh

sh::set_default "PAGER" "/usr/bin/less"

main() {
  "${PAGER}" "${_JIFF_ROOT}/libexec/jiff-$1"
}

usage() {
  printf "Usage: jiff task-show TASK\n"
}

return 0 2>/dev/null || true
sh::strict_mode on
main "$@"
