#!/usr/bin/env bash

source stdlib
source arraylib

RoleLink="${RoleLink:-${_JIFF_ROOT}/role/current}"
ContextLink="${ContextLink:-${_JIFF_ROOT}/context/current}"

main () {
  local context
  local contexts
  local hosts
  local hostname

  is_file "${RoleLink}" || jiff role admin
  is_not_file "${ContextLink}" || exit 0
  contexts=( jiff _data -g hosts.keys )
  hostname="$(hostname)"
  for context in "${contexts[@]}"; do
    hosts=( jiff _data -g "hosts.${context}" )
    if array_contains "${hostname}" "$hosts[@]"; then
      jiff context "${context}"
    fi
  done
}

return 2>/dev/null || true
strict_mode on
main "${@}"
