#!/usr/bin/env bash
# Usage: jiff jiff-reinstall
# Summary: Reinstall jiff

source stdlib

strict_mode on
# trace on # for debugging while developing

# TODO: make this read the deps file
current="$(jiff context | tail -1 | cut -d " " -f3)" # TODO: make this read the link and maybe put in jifflib?
basher uninstall binaryphile/bash-libs
basher uninstall binaryphile/jiff-core
# TODO: make this uninstall the user's jiff, not mine
basher uninstall binaryphile/jiff-personal
# TODO: make this install the user's jiff, not mine
basher install binaryphile/jiff-personal
jiff context "${current}"
