#!/usr/bin/env bash
# Usage: jiff jiff-update
# Summary: Update jiff

source stdlib

# TODO: read deps from package.sh
main () {
  local current

  basher upgrade binaryphile/bash-libs
  basher upgrade binaryphile/jiff-core
  current="$(jiff show context)"
  cd "${_JIFF_ROOT}"
  jiff set context none
  git checkout -- .
  git fetch
  git reset --hard origin/master
  jiff set context "${current}"
}

return 0 2>/dev/null || true
strict_mode on
main "${@}"
