#!/usr/bin/env bash
# Summary: choose a set of tasks based on context and, optionally,
# distribution
#
# Usage:
#   jiff set context [-d <distro>|--distro=<distro>] (<context>|none)
#
# Options:
#   <distro>    One of: rhel-6|centos-6|ubuntu-14|ubuntu-15
#   <context>   One of: avwob|armt|office|peak10

source std.sh
source array.sh
source jiff.sh

declare -r LibExecDir="${_JIFF_ROOT}/libexec"
declare -r DistroLink="${_JIFF_ROOT}/distro/current"
declare -r RoleLibLink="${_JIFF_ROOT}/lib/rolelib"
declare -r ContextLink="${_JIFF_ROOT}/context/current"
declare -r RoleLink="${_JIFF_ROOT}/role/current"

main() {
  local context
  local distro
  local distros

  context="${1:-}"
  distro="${2:-}"
  if std::is_empty "${context}"; then
    usage
    exit 1
  fi
  if std::is_match "${context}" "none"; then
    remove_links
    make_rolelinks
    exit 0
  fi
  distros=( $(available_distros) )
  std::is_not_empty "${distro}" || distro="$(dist::detect_os)"
  if ary::contains "${distro}" "${distros[@]}"; then
    remove_links
    make_rolelinks
    make_links "${context}" "${distro}"
    exit 0
  fi
}

available_contexts() {
  printf "%s/context/*" "${_JIFF_ROOT}/context/*" | grep -v current
}

available_distros() {
  printf "%s/distro" "${_JIFF_ROOT}"
}

make_links() {
  local context
  local distro
  local role
  local file
  local task

  context="$1"
  distro="$2"
  std::is_link "${RoleLink}" || jiff role admin
  role="$(readlink "${RoleLink}")"
  std::make_symlink "${ContextLink}" "${context}/${distro}/${role}"
  std::make_symlink "${DistroLink}" "${distro}"
  std::make_symlink "${RoleLibLink}" "../distro/${distro}/${role}lib"
  for file in "${ContextLink}"/jiff-*; do
    std::is_match "${file}" "${ContextLink}/jiff-*" && continue
    task="$(std::base_name "${file}")"
    std::make_symlink "${LibExecDir}/${task}" "${file}"
  done
}

remove_links() {
  local file
  local link
  local links

  for file in "${ContextLink}"/jiff-*; do
    link="$(std::base_name "${file}")"
    rm -f "${LibExecDir}/${link}"
  done
  read -d "" -a links <<EOM || true
${ContextLink}
${DistroLink}
${RoleLibLink}
EOM
  for link in "${links[@]}"; do
    rm -f "${link}"
  done
}

usage() {
# TODO: fill in contexts from $Distros
  cat <<EOM
Usage:
  jiff set context [-d <distro>|--distro=<distro>] (<context>|none)

Options:
  <distro>    One of: rhel-6|centos-6|ubuntu-14|ubuntu-15
  <context>   One of: avwob|armt|office|peak10

Available contexts:

$(available_contexts)

EOM
}

return 0 2>/dev/null || true
std::strict_mode on
main "$@"
