#!/usr/bin/env bash
# Usage: jiff install PACKAGE

source sh.sh
source distro.sh
source jiff.sh

Verb="install"

main() {
  sh::run_subtask "${Verb}" "$@"
  dist::install_package "$1"
}

usage() {
  printf "Usage: jiff %s PACKAGE\n" "${Verb}"
}

return 0 2>/dev/null || :
sh::strict_mode on
main "$@"
