#!/usr/bin/env bash
# Usage: jiff task [new]
# Summary: Manage jiff tasks

source stdlib
# source jifflib # jiff-specific functions
# source platformlib # platform-specific functions

strict_mode_on
# trace_on # for debugging while developing

# Provide jiff completions
if match "${1:-}" "--complete"; then
  cat <<EOM
--option-one
--option-two
subtask
EOM
  exit
fi

new_task () {
  local taskname
  local filename

  taskname="${1}"
  [[ -n "${taskname}" ]] || usage && exit
  filename="jiff-${taskname}"
  push_dir "${_JIFF_ROOT}"
  ! is_file "${filename}" || echoerr "Task already exists!" && exit 1
  install -m 755 "${_JIFF_ROOT}/../share/jiff/jiff-sample-task" "${filename}"
  ! shell_is_bash || tail -100 "${HOME}/.bash_history" >> "${filename}"
  pop_dir
  exec "${EDITOR}" "${_JIFF_ROOT}/${filename}"
}

usage () {
  echo "Usage: jiff task new [task_name]"
}

subtask="${1:-}"
shift

case "${subtask}" in
"new" )
  new_task "${@}"
  ;;
* )
  usage
  ;;
esac
