#!/usr/bin/env bash
# Usage: jiff update PACKAGE

source sh.sh
sh::is_not_file "${_JIFF_ROOT}/lib/distro.sh" || source distro.sh
source jiff.sh

Verb="update"

main() {
  jiff::run_subtask "${Verb}" "$@"
  update_package "$1"
}

usage() {
  printf "Usage: jiff %s PACKAGE\n" "${Verb}"
}

return 0 2>/dev/null || :
strict_mode on
main "$@"
