#!/usr/bin/env bash
# Usage: jiff context CONTEXT|none [rhel-6|centos-6|ubuntu-14|ubuntu-15]
# Summary: Add tasks which presume an os distribution, user role and set of available resources

source stdlib
source arraylib
source jifflib

LibExecDirectory="${LibExecDirectory:-${_JIFF_ROOT}/libexec}"
DistroLibLink="${DistroLibLink:-${_JIFF_ROOT}/lib/distrolib}"
RoleLibLink="${RoleLibLink:-${_JIFF_ROOT}/lib/rolelib}"
ContextLink="${ContextLink:-${_JIFF_ROOT}/context/current}"
RoleLink="${RoleLink:-${_JIFF_ROOT}/role/current}"

main () {
  local context
  local distro

  context="${1:-}"
  distro="${2:-}"
  if is_empty "${context}"; then
    usage
    report_current
    exit 0
  fi
  if match "${context}" "none"; then
    remove_links
    exit 0
  fi
  is_not_empty "${distro}" || distro="$(detect_os)"
  if array_contains "${distro}" "${Distros[@]}"; then
    remove_links
    make_links "${context}" "${distro}"
    exit 0
  fi

  usage
  exit 1
}

available_contexts () {
  # shellcheck disable=SC2010
  ls "${_JIFF_ROOT}/context" | grep -v current
}

available_distros () {
  ls "${_JIFF_ROOT}/distro"
}

Distros=( $(available_distros) )

make_links () {
  local context
  local distro
  local role
  local file
  local link

  context="${1}"
  distro="${2}"
  role="$(readlink "${RoleLink}")"
  make_symlink "${ContextLink}" "${context}/${distro}/${role}"
  make_symlink "${DistroLibLink}" "../distro/${distro}/distrolib"
  make_symlink "${RoleLibLink}" "../distro/${distro}/${role}lib"
  for file in "${ContextLink}"/jiff-*; do
    match "${file}" "${ContextLink}/jiff-*" && continue
    link="$(base_name "${file}")"
    make_symlink "${LibExecDirectory}/${link}" "${file}"
  done
}

remove_links () {
  local file
  local link
  local links

  for file in "${ContextLink}"/jiff-*; do
    link="$(base_name "${file}")"
    rm -f "${LibExecDirectory}/${link}"
  done
  read -d "" -a links <<EOM || true
${ContextLink}
${DistroLibLink}
${RoleLibLink}
EOM
  for link in "${links[@]}"; do
    rm -f "${link}"
  done
  make_rolelinks
}

report_current () {
  local current

  if is_link "${ContextLink}"; then
    current="$(readlink "${ContextLink}" | cut -d/ -f1)"
  else
    current=none
  fi
  cat <<EOM
Currently using: ${current}
EOM
}

usage () {
# TODO: fill in contexts from $Distros
  cat <<EOM
Usage: jiff context CONTEXT|none [rhel-6|centos-6|ubuntu-14|ubuntu-15]

Available contexts:

$(available_contexts)

EOM
}

return 2>/dev/null || true
strict_mode on
main "${@}"
