#!/usr/bin/env bash
# Usage: jiff task-add

source std.sh

std::set_default "EDITOR" "/usr/bin/vim"

main() {
  std::exit_if_is_empty "${1:-}"
  add_task "$@"
}

add_task() {
  local taskname
  local filename
  local task_dir

  taskname="${1}"
  filename="jiff-${taskname}"
  task_dir="$(set_taskdir "${2:-}")"
  cd "${_JIFF_ROOT}/libexec"
  cd "${task_dir}"
  std::exit_if_is_file "${filename}"
  copy_sample_task "${filename}" "${taskname}"
  "${EDITOR}" "${filename}"
  git add -f "${filename}"
  cd "${_JIFF_ROOT}/libexec"
  std::make_symlink "${filename}" "${task_dir}/${filename}"
}

copy_sample_task() {
  local filename
  local taskname

  filename="$1"
  taskname="$2"
  install -m 755 "${_JIFF_ROOT}/share/jiff/jiff-sample-task" "${filename}"
  sed -i -e "s|jiff sample-task|jiff ${taskname}|" "${filename}"
  if std::shell_is_bash && std::is_file "${HOME}/.bash_history"; then
    echo "" >> "${filename}"
    tail -50 "${HOME}/.bash_history" >> "${filename}"
  fi
}

set_taskdir() {
  case "$1" in
    "role" )
      printf "%s/role/current" "${_JIFF_ROOT}"
      ;;
    * )
      printf "%s/context/current" "${_JIFF_ROOT}"
  esac
}

return 0 2>/dev/null || true
std::strict_mode on
main "$@"
