#!/usr/bin/env bash
# Usage: jiff use [rhel-6|centos-6|ubuntu-14|ubuntu-15|auto|none]
# Summary: Add platform-specific tasks from the named platform

source stdlib

strict_mode_on

# Provide jiff completions
if match "${1:-}" "--complete"; then
  cat <<EOM
rhel-6
centos-6
ubuntu-14
ubuntu-15
auto
none
EOM
  exit
fi

LibExec="${_JIFF_ROOT}/libexec"
CurrentLink="${LibExec}/platforms/current"

make_links () {
  local platform
  local file
  local link

  platform="${1}"

  make_symlink "${CurrentLink}" "${platform}"
  for file in ${CurrentLink}/jiff-*; do
    link="$(base_name "${file}")"
    make_symlink "${LibExec}/${link}" "${file}"
  done
}

jiff_auto () {
  local platform

  exit_if_is_link "${CurrentLink}"
  platform="$(detect_os)"
  jiff use "${platform}"
}

remove_links () {
  local file
  local link

  for file in ${CurrentLink}/jiff-*; do
    link="$(base_name "${file}")"
    rm -f "${LibExec}/${link}"
  done
  rm -f "${CurrentLink}"
}

usage () {
  echo "Usage: jiff use [rhel-6|centos-6|ubuntu-14|ubuntu-15|auto|none]"
}

report_current () {
  if is_link "${CurrentLink}"; then
    current="$(readlink "${CurrentLink}")"
    current="${current##*/}"
  else
    current=none
  fi
  echo "Currently using: ${current}"
}

platform="${1:-}"

case "${platform}" in
"rhel-6" | "centos-6" | "ubuntu-14" | "ubuntu-15" )
  make_links "${platform}"
  ;;
"auto" )
  jiff_auto
  ;;
"none" )
  remove_links
  ;;
* )
  usage
  report_current
  ;;
esac
