#!/usr/bin/env bash
# Usage: jiff edit

source stdlib
source jifflib

Verb="show"

main () {
  run_subtask "${Verb}" "$@"
}

usage () {
  echo "Usage: jiff ${Verb} TASK"
}

return 0 2>/dev/null || true
strict_mode on
main "$@"
