#!/usr/bin/env bash
# Usage: jiff context CONTEXT|none [rhel-6|centos-6|ubuntu-14|ubuntu-15]
# Summary: Add tasks which presume an os distribution, user role and set of available resources

source stdlib

strict_mode on

LibExec="${_JIFF_ROOT}/libexec"
DistroLink="${_JIFF_ROOT}/lib/distrolib"
RoleLink="${_JIFF_ROOT}/lib/rolelib"
ContextLink="${_JIFF_ROOT}/context/current"

available_contexts () {
  ls "${_JIFF_ROOT}/context"
}

make_links () {
  local context="${1}"
  local distro="${2}"
  local file
  local link

  make_symlink "${ContextLink}" "${context}/${distro}/role"
  make_symlink "${DistroLink}" "../distro/${distro}/distro"
  make_symlink "${RoleLink}" "../distro/${distro}/role"
  for file in ${ContextLink}/jiff-*; do
    link="$(base_name "${file}")"
    make_symlink "${LibExec}/${link}" "${file}"
  done
}

remove_links () {
  local file
  local link

  for file in ${DistroLink}/jiff-*; do
    link="$(base_name "${file}")"
    rm -f "${LibExec}/${link}"
  done
  for link in "${ContextLink}" "${DistroLink}" "${RoleLink}"; do
    rm -f "${link}"
  done
}

usage () {
  cat <<EOM
Usage: jiff context CONTEXT|none [rhel-6|centos-6|ubuntu-14|ubuntu-15]

Available contexts:

$(ls "${_JIFF_ROOT}/context")

EOM
}

report_current () {
  local current

  if is_link "${ContextLink}"; then
    current="$(readlink "${ContextLink}")"
  else
    current=none
  fi
  cat <<EOM
Currently using: ${current}

EOM
}

context="${1:-}"
distro="${2:-}"

if is_empty "${context}"; then
  usage
  report_current
  exit 0
fi

if match "${context}" "none"; then
  remove_links
  exit 0
fi

! is_empty "${distro}" || distro="$(detect_os)"

case "${distro}" in
  "rhel-6" | "centos-6" | "ubuntu-14" | "ubuntu-15" )
    remove_links
    make_links "${context}" "${distro}"
    ;;
  * )
    usage
    exit 1
    ;;
esac
